name: MobKills
version: '${project.version}'
main: com.matrunchyk.mobkillsplugin.MobKillsPlugin
description: A plugin that tracks the number of mobs killed by each player.
author: Serhii Matrunchyk
api-version: 1.19
load: STARTUP
website: https://matrunchyk.com

commands:
  daddy-power:
    description: Gives players a "Daddy Power" kit
    usage: /daddy-power
  happy-birthday:
    description: Send happy b-day wishes to a player
    usage: /happy-birthday
  debug:
    description: Debug
    usage: /debug
