name: Build and publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: MobKillsPlugin
          path: build/libs/MobKillsPlugin-1.0-SNAPSHOT.jar

      - name: Publish to release
        id: publish
        uses: actions/upload-release-asset@v1
        with:
          asset_path: build/libs/MobKillsPlugin-1.0-SNAPSHOT.jar
          asset_name: MobKillsPlugin-1.0-SNAPSHOT.jar
          asset_content_type: application/java-archive
          tag_name: ${{ github.ref }}
          release_id: ${{ env.RELEASE_ID }}
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
