name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create tag
        id: create_tag
        if: success()
        run: |
          echo ::set-output name=tag::v1.0.$(date +'%Y%m%d%H%M%S')
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/MobKillsPlugin-1.0-SNAPSHOT.jar
          draft: false
          prerelease: false
          generate_release_notes: true
