name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: latest
          name: latest
          draft: false
          skipIfReleaseExists: true
          allowUpdates: true
          removeArtifacts: true
          prerelease: false
          generateReleaseNotes: true
          omitBody: true
          artifacts: "target/MobKillsPlugin-1.0-SNAPSHOT.jar"
          artifactContentType: "application/java-archive"
          commit: "main"
